$text_color = rgba(220,215,186,0.9)
general {
    ignore_empty_input = true
    hide_cursor = true
    fail_timeout = 1250
}

background {
    monitor = 
#    path = $HOME/Pictures/Wallpapers/Creation_of_Adam_everforest.jpeg
#    path = screenshot
    path = $HOME/.config/wallpapers/Creation_of_Adam_everforest.jpeg
    blur_passes = 2 # 0 disables blurring
    blur_size = 3
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.5172
    vibrancy = 0.1696
    vibrancy_darkness = 0.5
}

#GREETINGS
label {
    monitor = 
    text = $USER #cmd[update:1000] echo "$(date +'%A, %B %d)"
    color = $text_color #rgba(220,215,186,0.9)
    font_size = 18
    font_family = SF Pro Display 
    shadow_phases = 2
    shadow_size = 1
    position = 0, -150
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    color = $text_color
    font_size = 115
    font_family = SF Pro Display Bold
    position = 0, -300
    halign = center
    valign = top
}

#BATTERY
label {
    monitor =
    text = cmd[update:10000] echo "Batt percentage: $(upower -i /org/freedesktop/UPower/devices/battery_BAT1 | grep percentage | awk '{print $2}')"
    color = $text_color
    font_size = 14
    font_family = SF Pro Display
    position = -20, 20
    halign = right
    valign = down
}

#AVATAR
image {
    monitor =
    path = $HOME/.config/wallpapers/avatar.jpeg
    size = 150
    valign = center
    halign = center
    border_size = 2
    rounding = 0
    position = 0, -30
    border_color = rgba(211, 198, 170, 1)
}

#DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = $text_color
    font_size = 26
    font_family = SF Pro Display Bold
    position = -20, -20
    halign = right
    valign = top
}

#LAYOUT
label {
    monitor =
    text = $LAYOUT
    color = $text_color
    font_size = 14
    font_family = SF Pro Display
    position = -20, 50
    halign = right
    valign = down
}

input-field {
    monitor = 
    inner_color = rgba(211, 198, 170, 1)
    outer_color = rgba(45, 53, 59, 1)
    font_color = rgba(45, 53, 59, 1)
    fade_timeout = 0
    size = 300, 40
    position = 0, -200
    halign = center
    valign = center
    outline_thickness = 2
    font_family = SF Pro Display Bold
    font_size = 16
    check_color = rgba(167, 192, 128, 1)
    fail_color = rgba(230,126,128,1.0)
}
